### ISSUE TITLE
Undefined class constant 'CONTRIBUTOR_ROLE'

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#323]
The error below is thrown when trying to use modules that define content types when localgov_core is a version less than 2.1.

Simple solution is to bump the core requirement for all these modules to ^2.1

```
Error: Undefined class constant 'CONTRIBUTOR_ROLE' in /app/web/modules/contrib/localgov_subsites/localgov_subsites.module on line 82 #0 /app/web/modules/contrib/localgov_core/modules/localgov_roles/src/RolesHelper.php(45): localgov_subsites_localgov_roles_default()
#1 /app/web/modules/contrib/localgov_core/modules/localgov_roles/src/RolesHelper.php(24): Drupal\localgov_roles\RolesHelper::getModuleRoles('localgov_subsit...')
#2 /app/web/modules/contrib/localgov_core/modules/localgov_roles/localgov_roles.module(15): Drupal\localgov_roles\RolesHelper::assignModuleRoles('localgov_subsit...')
#3 [internal function]: localgov_roles_modules_installed(Array, false)
#4 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('localgov_roles_...', Array)
#5 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(367): Drupal\Core\Extension\ModuleHandler->invokeAll('modules_install...', Array)
#6 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#7 /app/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(103): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#8 [internal function]: Drush\Drupal\Commands\pm\PmCommands->enable(Array, Array)
#9 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#10 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(313): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#20 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#21 {main}
Error: Undefined class constant &#039;CONTRIBUTOR_ROLE&#039; in localgov_subsites_localgov_roles_default() (line 82 of /app/web/modules/contrib/localgov_subsites/localgov_subsites.module).
```

**Comment by stephen-cox** [comment]
Related issue localgovdrupal/localgov_workflows#2

**Comment by stephen-cox** [comment]
Should be fixed with the latest raft of fixes and releases.
